# .github/workflows/prettier.yml
name: Prettier

on:
  push:
    branches: [ master ] # Ejecutar en push a la rama main
  pull_request:
    branches: [ master ] # Ejecutar en PR a la rama main

jobs:
  auto-format:
    name: Formatear y lint
    runs-on: ubuntu-latest

    steps:
      - name: Descarga de repositorio
        uses: actions/checkout@v4 

      - name: Configuracion de  Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '22' 

      - name: Instalacion de dependencias
        run: npm i
      - name: Formatear Typescript
        run: npm run format
